reichert621/health

package.json, server/javascript/db/models/scorecard.js, server/javascript/db/models/scorecard_selected_task.js
Fix updating selected tasks in by deleting scorecard tasks before re-submitting.
Fixes #13
=> Fix updating selected tasks in scorecard

client/react/app/components/checklist/CheckList.js, client/react/app/components/scorecard/NewScoreCard.js, client/react/app/components/scorecard/ScoreCard.js, client/react/app/helpers/http.ts, client/react/app/helpers/scorecard.ts, client/react/app/helpers/tasks.ts, server/javascript/api.js, server/javascript/db/models/scorecard.js, server/javascript/db/models/scorecard_selected_task.js
Automatically save existing scorecards when toggling tasks or updating the date.
Fixes #12
=> Auto-save existing scorecards

client/react/app/App.less, client/react/app/components/scorecard/NewScoreCard.js, client/react/app/components/scorecard/ScoreCard.js, client/react/app/components/scorecard/ScoreCard.less, client/react/app/components/scorecard/ScoreCardOverview.js, client/react/app/components/scorecard/TaskCheckbox.js
=> Update design of scorecard view

client/react/app/App.less, client/react/app/components/checklist/CheckList.js, client/react/app/components/checklist/CheckList.less, client/react/app/components/checklist/CheckListQuestion.js, client/react/app/components/checklist/NewCheckList.js
=> Add descriptions to checklist answers

client/assets/checkmark.svg, client/assets/pencil.svg, client/react/app/App.less, client/react/app/components/checklist/CheckList.js, client/react/app/components/dashboard/Dashboard.js, client/react/app/components/dashboard/Dashboard.less, client/react/app/components/dashboard/DashboardList.js, client/react/app/components/dashboard/DashboardPreview.js, client/react/app/components/dashboard/DashboardReporting.js, client/react/app/components/reporting/ReportingChart.js, client/react/app/components/scorecard/NewScoreCard.js, client/react/app/components/scorecard/ScoreCard.js, client/react/app/components/scorecard/ScoreCardOverview.js, client/react/app/helpers/utils.ts
=> Start redesigning the dashboard

client/react/app/components/checklist/CheckList.js, client/react/app/components/dashboard/Dashboard.js, client/react/app/components/dashboard/DashboardPreview.js, server/javascript/db/models/checklist.js, server/javascript/db/models/scorecard.js
=> Auto-create scorecards and checklists from dashboard

client/react/app/App.js, client/react/app/App.less, client/react/app/components/tasks/TaskList.js, client/react/app/components/tasks/index.js, client/react/app/helpers/tasks.ts, server/javascript/api.js, server/javascript/db/index.js, server/javascript/db/models/category.js, server/javascript/db/models/scorecard.js
Fixes #29 
TODO: improve design of this view! (in a separate PR)
=> Create simple UI where user can manage tasks

client/react/app/App.less, client/react/app/components/checklist/CheckList.js, client/react/app/components/checklist/CheckList.less, client/react/app/components/dashboard/Dashboard.js, client/react/app/components/home/Home.less, client/react/app/components/home/Login.js, client/react/app/components/navbar/NavBar.js, client/react/app/components/navbar/index.js, client/react/app/components/scorecard/ScoreCard.js, client/react/app/components/tasks/TaskList.js
=> Create a simple navbar

client/react/app/App.js, client/react/app/components/home/Home.less, client/react/app/components/home/Login.js, client/react/app/components/home/SignUp.js, client/react/app/components/home/SignUpComplete.js, client/react/app/components/home/index.js, client/react/app/helpers/auth.ts, server/javascript/api.js, server/javascript/db/models/user.js, server/javascript/db/seeds/categories.js, server/javascript/db/seeds/checklist_questions.js, server/javascript/db/seeds/checklists.js, server/javascript/db/seeds/entries.js, server/javascript/db/seeds/scorecards.js, server/javascript/db/seeds/tasks.js, server/javascript/db/seeds/users.js
=> Set up simple signup flow

client/react/app/components/scorecard/ScoreCard.js, server/javascript/db/models/default_tasks.js, server/javascript/db/models/user.js
=> Create a list of default tasks for new users

client/react/app/App.less, client/react/app/components/dashboard/Dashboard.js, client/react/app/components/dashboard/Dashboard.less, client/react/app/components/dashboard/DashboardReporting.js, client/react/app/components/reporting/ReportingChart.js
=> Allow toggle between list and chart view in dashboard UI

client/react/app/App.less, client/react/app/components/tasks/CategoryTasks.js, client/react/app/components/tasks/Task.less, client/react/app/components/tasks/TaskItem.js, client/react/app/components/tasks/TaskList.js, client/react/app/helpers/tasks.ts, server/javascript/api.js, server/javascript/db/models/task.js
=> Allow creating and editing tasks in task management view

client/react/app/components/reporting/Reporting.js, client/react/app/components/tasks/TopTasks.js, client/react/app/helpers/reporting.ts, client/react/app/helpers/tasks.ts, server/javascript/api.js, server/javascript/db/models/task.js
=> Write API for top selected tasks

client/react/app/components/tasks/CategoryTasks.js, server/javascript/api.js, server/javascript/db/controllers/categories.js, server/javascript/db/controllers/checklist_questions.js, server/javascript/db/controllers/checklist_scores.js, server/javascript/db/controllers/checklists.js, server/javascript/db/controllers/entries.js, server/javascript/db/controllers/index.js, server/javascript/db/controllers/scorecards.js, server/javascript/db/controllers/tasks.js, server/javascript/db/controllers/users.js, server/javascript/db/controllers/utils.js
Fixes #41 
TODO: QA this a bit before merging.
=> Refactor API methods into controller files

client/react/app/App.js, client/react/app/components/home/About.js, client/react/app/components/home/Home.less, client/react/app/components/home/Login.js, client/react/app/components/home/SignUp.js, client/react/app/components/home/index.js, client/react/app/components/navbar/NavBar.js
=> Set up the "About" page

client/react/app/App.less, client/react/app/components/checklist/CheckList.less, client/react/app/components/checklist/CheckListQuestion.js, client/react/app/components/dashboard/Dashboard.less, client/react/app/components/navbar/NavBar.less, client/react/app/components/scorecard/ScoreCard.less
Minor tweaks for smaller screens.
=> Attempt to make design a bit more mobile friendly

client/assets/check.svg, client/react/app/App.less, client/react/app/components/scorecard/ScoreCard.js
=> Indicate when the scorecard is saving/saved

client/react/index.html
=> [small] Update title

client/react/app/components/reporting/Reporting.js, client/react/app/components/reporting/ReportingChart.js, client/react/app/components/reporting/ScoresByCategory.js, client/react/app/components/reporting/ScoresByDay.js, client/react/app/components/reporting/TopTasks.js, client/react/app/helpers/reporting.ts, client/react/app/helpers/utils.ts, server/javascript/api.js, server/javascript/db/controllers/checklists.js, server/javascript/db/controllers/index.js, server/javascript/db/controllers/reporting.js, server/javascript/db/controllers/scorecards.js, server/javascript/db/models/checklist.js, server/javascript/db/models/scorecard.js, server/javascript/db/models/scorecard_selected_task.js
Initial work on #58 (no UI included yet)
**TODOs**:
=> Improve reporting APIs

client/assets/plus-gray.svg, client/react/app/components/home/About.js, client/react/app/components/scorecard/ScoreCard.less, client/react/app/components/tasks/CategoryTasks.js, client/react/app/components/tasks/Task.less, client/react/app/components/tasks/TaskItem.js, client/react/app/components/tasks/TaskList.js, server/javascript/db/models/scorecard.js, server/javascript/db/models/task.js
=> Allow deactivation of tasks

.gitignore, client/react/app/components/reporting/MoodFrequency.js, client/react/app/components/reporting/Reporting.js, client/react/app/components/reporting/TopTasks.js, client/react/app/components/reporting/TotalPointsChart.js, client/react/app/components/tasks/Task.less, client/react/app/helpers/utils.ts, server/javascript/db/controllers/reporting.js, server/javascript/db/models/checklist.js, server/javascript/db/models/scorecard.js
Just some extra UI components to include in the reporting dashboard:
Also adds:
**TODO**: come up with better design for reporting dashboard!
=> Add simple component for mood frequency

client/react/app/components/dashboard/Dashboard.js, client/react/app/components/scorecard/Scorecard.tsx, client/react/app/helpers/scorecard.ts, client/react/app/helpers/utils.ts, client/react/app/reducers/index.js, client/react/app/store.js, package-lock.json, package.json
Redux proof of concept in `Dashboard` component:
=> Initial setup of Redux

client/react/app/components/navbar/NavBar.tsx, client/react/app/components/reporting/MoodFrequency.js, client/react/app/components/reporting/Reporting.js, client/react/app/components/reporting/Reporting.less, client/react/app/components/reporting/ReportingOverview.js, client/react/app/components/reporting/ReportingStreaks.js, client/react/app/components/reporting/ScoresByCategory.js, client/react/app/components/reporting/ScoresByDay.js, client/react/app/components/reporting/TopTasks.js
This PR just begins creating the rough layout for the reporting page.
=> Prep reporting view for future redesign

client/react/app/App.js, client/react/app/components/dashboard/Dashboard.less, client/react/app/components/self-activation/SelfActivationMethods.tsx, client/react/app/components/self-activation/index.ts, client/react/app/components/self-activation/methods.ts
=> Add view for Self-Activation Methods

client/react/app/App.js, client/react/app/components/checklist/CheckList.less, client/react/app/components/checklist/Checklist.tsx, client/react/app/components/checklist/ChecklistContainer.tsx, client/react/app/components/checklist/ChecklistFlow.tsx, client/react/app/components/checklist/ChecklistFlowQuestion.tsx, client/react/app/components/checklist/index.js, package.json
=> Alternative check-in flow

client/react/app/components/reporting/HighImpactTasks.tsx, client/react/app/components/reporting/Reporting.js, client/react/app/components/reporting/TopMoods.tsx, client/react/app/components/reporting/index.js, client/react/app/helpers/reporting.ts, server/javascript/db/controllers/reporting.js
=> Add some more reporting components for fun

client/react/app/App.js, client/react/app/App.less, client/react/app/components/dashboard/Dashboard.js, client/react/app/components/dashboard/DashboardPreview.js, client/react/app/components/entry/Entry.less, client/react/app/components/entry/EntryContainer.tsx, client/react/app/components/entry/EntryPreview.js, client/react/app/components/entry/UserEntryContainer.tsx, client/react/app/components/entry/index.js, client/react/app/components/home/Home.js, client/react/app/components/home/Profile.js, client/react/app/helpers/entries.ts, server/javascript/db/models/entry.js
=> Allow users to make blog posts public for sharing

client/react/app/App.js, client/react/app/App.less, client/react/app/components/self-activation/DailyGratitude.tsx, client/react/app/components/self-activation/SelfActivation.less, client/react/app/components/self-activation/index.ts, client/react/app/helpers/gratitudes.ts, server/javascript/api.js, server/javascript/db/controllers/gratitudes.js, server/javascript/db/controllers/index.js, server/javascript/db/index.js, server/javascript/db/migrations/20180317145935_gratitudes.js, server/javascript/db/models/gratitude.js
=> Set up "Daily Gratitude" feature

client/react/app/App.less, client/react/app/components/navbar/NavBar.less, client/react/app/components/navbar/NavBar.tsx, client/react/app/helpers/auth.ts, client/react/app/helpers/utils.ts, client/react/app/reducers/index.ts, server/javascript/db/controllers/users.js
=> Add dropdown menu to navbar

client/react/app/components/self-activation/DailyImperatives.tsx, client/react/app/components/tasks/Task.less
=> Simplify Dos and Donts list UI

client/react/app/components/home/Home.js, client/react/app/components/navbar/NavBar.tsx, client/react/app/components/self-activation/methods.ts, package-lock.json, package.json, server/javascript/config.js, server/javascript/index.js
=> Store session in Postgres rather than in memory

.travis.yml, client/react/app/components/reporting/MoodFrequency.tsx, client/react/app/components/reporting/MoodFrequencyChart.tsx, client/react/app/components/reporting/MoodReportingTable.tsx, client/react/app/components/reporting/Reporting.tsx, client/react/app/components/reporting/TaskReportingTable.tsx, client/react/app/helpers/__test__/reporting.spec.ts, client/react/app/helpers/reporting.ts, client/react/app/types/index.d.ts, package.json
Task reporting:
Mood reporting:
Mood frequency chart:
=> Set up experimental reporting components

client/react/app/App.js, client/react/app/components/reporting/MoodReporting.tsx, client/react/app/components/reporting/MoodReportingChart.tsx, client/react/app/components/reporting/TaskReporting.tsx, client/react/app/components/reporting/TaskReportingChart.tsx, client/react/app/components/reporting/index.ts, client/react/app/helpers/reporting.ts, server/javascript/api.js, server/javascript/db/controllers/checklists.js, server/javascript/db/controllers/scorecards.js, server/javascript/db/models/checklist.js, server/javascript/db/models/checklist_score.js, server/javascript/db/models/scorecard.js, server/javascript/db/models/scorecard_selected_task.js, server/javascript/db/models/utils.js
Set up more in-depth views of task and mood analytics.
=> Set up additional reporting metrics

client/react/app/App.js, client/react/app/components/_experimental/index.js, client/react/app/components/_experimental/v2.js, client/react/app/components/_experimental/v2.less, client/react/app/components/scorecard/ScorecardSmall.tsx, client/react/app/components/scorecard/index.js, client/react/app/components/self-activation/DailyGratitudeSmall.tsx, client/react/app/components/self-activation/DailyImperatives.tsx, client/react/app/components/self-activation/index.ts, client/react/app/components/tasks/Task.less
This PR just sets up some components to play around with for v2 of the workflow.
For reference, this is the current dashboard:
One of the things we might want to change about the current design is the amount of real estate given to the table/list of previous dates. I think it would be better to just focus on everything the user needs to accomplish **today**.
Here's a simplified version of one option I was considering. In this flow, the app would guide the user through each step of things to do throughout the day, denote progress somewhere, reward the user for accomplishments, etc. It would also explain each step and why each is important.
An alternative could be just cramming as much into one view as possible. Each card represents a step/task in the daily process, and contains a preview …
=> Setup of some experimental designs for v2

client/react/app/components/checklist/Checklist.tsx, client/react/app/components/checklist/ChecklistContainer.tsx, client/react/app/components/checklist/ChecklistFlow.tsx, client/react/app/helpers/checklist.ts, server/javascript/api.js, server/javascript/db/controllers/checklists.js, server/javascript/db/models/checklist.js, server/javascript/db/models/checklist_score.js
=> Auto save check-in answers

package.json
=> Test webpack production build

client/react/app/App.less, client/react/app/components/navbar/NavBar.tsx, client/react/app/components/tasks/Dropdown.tsx, client/react/app/components/tasks/Task.less, client/react/app/components/tasks/TaskItem.tsx, server/db/models/task.js
Assign task points from dropdown instead of free form text field.
Fixes #117
=> Assign task points from dropdown

client/react/app/components/tasks/CategoryTasks.tsx, client/react/app/components/tasks/Dropdown.tsx, client/react/app/components/tasks/TaskItem.tsx, client/react/app/helpers/tasks.ts, client/react/app/helpers/utils.ts
Converts new task points input from text field to dropdown.
=> Fix points dropdown input for new tasks

client/react/app/components/reporting/TaskReportingTable.tsx, client/react/app/components/scorecard/Scorecard.tsx, client/react/app/helpers/reporting.ts, client/react/app/helpers/tasks.ts, server/api.js, server/db/controllers/tasks.js, server/db/models/task.js
Includes:
- `simple`: the easiest habits to accomplish (based on point value)
- `favorites`: the user's most commonly accomplished habits
- `neglected`: the user's least commonly accomplished habits
=> Set up API for task suggestions

client/react/app/components/checklist/ChecklistContainer.tsx, client/react/app/components/scorecard/Scorecard.tsx, client/react/app/reducers/index.ts
Start moving more logic to redux:
=> Improve redux usage in scorecard and checklist

client/react/app/App.less, client/react/app/components/dashboard/Today.tsx, client/react/app/components/entry/EntryContainer.tsx, client/react/app/components/scorecard/ChallengeCheckbox.tsx, client/react/app/components/scorecard/Scorecard.tsx, client/react/app/components/scorecard/ScorecardContainer.tsx, client/react/app/components/tasks/ChallengeList.tsx, client/react/app/components/tasks/Task.less, client/react/app/components/tasks/TaskList.tsx, client/react/app/helpers/challenges.ts, client/react/app/helpers/utils.ts, client/react/app/reducers/index.ts, server/api.js, server/db/controllers/challenges.js, server/db/controllers/index.js, server/db/index.js, server/db/migrations/20180425160734_challenges.js, server/db/models/challenge.js, server/db/models/challenge_member.js, server/db/models/scorecard_selected_task.js, server/db/models/user_accomplished_challenge.js, server/db/models/user_accomplished_challenges.js
=> Experimental "Challenges" feature

client/react/app/App.less, client/react/app/components/dashboard/Dashboard.less, client/react/app/components/dashboard/DashboardPreview.tsx, client/react/app/components/dashboard/Today.tsx, client/react/app/components/navbar/NavBar.tsx, client/react/app/components/reporting/Reporting.tsx, client/react/app/components/scorecard/Scorecard.tsx, client/react/app/components/scorecard/TaskCheckbox.tsx, client/react/app/components/tasks/CategoryTasks.tsx, client/react/app/components/tasks/SuggestionsList.tsx, client/react/app/components/tasks/Task.less, client/react/app/components/tasks/TaskItem.tsx, client/react/app/components/tasks/TaskList.tsx, client/react/app/helpers/tasks.ts, server/api.js, server/db/controllers/categories.js, server/db/controllers/tasks.js, server/db/models/category.js, server/db/models/default_tasks.js, server/db/models/task.js, server/db/models/user.js
=> Update "Task Settings" view

client/react/app/components/dashboard/Dashboard.less, client/react/app/components/dashboard/Today.tsx, client/react/app/components/dashboard/TodayProgressBar.tsx, client/react/app/helpers/scorecard.ts, server/api.js, server/db/controllers/scorecards.js, server/db/models/scorecard.js
Measures today's productivity against average/high scores.
=> Set up experimental "Today's Progress" bar

client/react/app/App.tsx, client/react/app/components/checklist/Checklist.tsx, client/react/app/components/checklist/ChecklistContainer.tsx, client/react/app/components/checklist/ChecklistFlow.tsx, client/react/app/components/checklist/ChecklistSample.tsx, client/react/app/components/checklist/index.ts, client/react/app/helpers/cache.ts, client/react/app/helpers/checklist.ts
=> Checklist view for non-authenticated users

client/react/app/App.tsx, client/react/app/components/scorecard/ScorecardSample.tsx, client/react/app/components/scorecard/index.ts, client/react/app/helpers/tasks.ts, server/api.js, server/db/models/user.js
=> Scorecard view for non-authenticated users

client/react/app/App.tsx, client/react/app/components/assessment/AssessmentSample.tsx, client/react/app/components/assessment/index.ts, client/react/app/components/checklist/Checklist.tsx, client/react/app/components/checklist/ChecklistContainer.tsx, client/react/app/components/checklist/ChecklistFlow.tsx, client/react/app/helpers/assessment.ts, client/react/app/helpers/checklist.ts, package.json, server/api.js, server/db/controllers/assessments.js, server/db/controllers/index.js, server/db/index.js, server/db/migrations/20180531105505_assessments.js, server/db/models/assessment.js, server/db/models/assessment_question.js, server/db/models/checklist.js, server/db/models/user_assessment.js, server/db/models/user_assessment_score.js
=> Set up additional assessments

client/react/app/App.tsx, client/react/app/components/assessment/AssessmentContainer.tsx, client/react/app/components/assessment/index.ts, client/react/app/components/dashboard/Dashboard.less, client/react/app/components/dashboard/Dashboard.tsx, client/react/app/components/dashboard/DashboardList.tsx, client/react/app/components/dashboard/DashboardPreview.tsx, client/react/app/components/dashboard/DashboardReporting.tsx, client/react/app/components/dashboard/Today.tsx, client/react/app/components/reporting/Reporting.tsx, client/react/app/components/reporting/ReportingChart.tsx, client/react/app/helpers/assessment.ts, client/react/app/helpers/reporting.ts, client/react/app/helpers/utils.ts, client/react/app/reducers/index.ts, server/api.js, server/db/controllers/assessments.js, server/db/controllers/reporting.js, server/db/models/assessment.js, server/db/models/assessment_question.js, server/db/models/user_assessment.js
Sets up all the basic functionality for #155
=> Create additional assessments for anxiety and well-being

client/react/app/components/reporting/HighImpactTasks.tsx, client/react/app/components/reporting/Reporting.less, client/react/app/components/reporting/Reporting.tsx, client/react/app/components/reporting/ReportingAverages.tsx, client/react/app/components/reporting/ReportingStreaks.tsx, client/react/app/components/reporting/ScoresByDay.tsx, client/react/app/helpers/reporting.ts, server/db/controllers/reporting.js, server/db/migrations/20180619183318_checklists_to_assessments.js, server/db/models/assessment.js, server/db/models/checklist.js, server/db/models/user_assessment_score.js, server/db/models/utils.js
=> Assessment analytics

client/react/app/components/dashboard/Dashboard.tsx, client/react/app/components/dashboard/DashboardList.tsx, client/react/app/components/dashboard/DashboardPreview.tsx, client/react/app/components/dashboard/Today.tsx, client/react/app/components/reporting/ReportingChart.tsx, client/react/app/reducers/assessments.ts
=> Deprecate checklist from dashboard

server/api.js, server/db/controllers/reporting.js, server/db/models/assessment.js, server/db/models/checklist.js, server/db/models/scorecard.js, server/db/models/user_accomplished_challenge.js
=> Add methods to fetch stats for current and previous month

client/react/app/components/dashboard/Dashboard.tsx, client/react/app/components/dashboard/DashboardReporting.tsx, client/react/app/components/dashboard/Today.tsx, client/react/app/components/reporting/Reporting.tsx, client/react/app/helpers/reporting.ts, client/react/app/helpers/utils.ts, client/react/app/reducers/stats.ts, server/db/controllers/checklists.js, server/db/controllers/reporting.js, server/db/controllers/scorecards.js, server/db/models/assessment.js, server/db/models/checklist.js, server/db/models/checklist_score.js, server/db/models/scorecard.js, server/db/models/scorecard_selected_task.js, server/db/models/task.js, server/db/models/user_assessment.js, server/db/models/user_assessment_score.js, server/db/models/utils.js
=> Allow filtering stats by date range in API

.gitignore, client/react/app/components/reporting/TaskReporting.tsx, client/react/app/components/reporting/TaskReportingChart.tsx, client/react/app/components/reporting/TaskReportingTable.tsx, client/react/app/helpers/__test__/reporting.spec.ts, client/react/app/helpers/reporting.ts, server/api.js, server/db/controllers/assessments.js, server/db/models/assessment.js, server/db/models/user_assessment_score.js
Task reports were using outdated data from the old Checklist model (rather than the new Assessment model)
=> Update some assessment reporting APIs

client/react/app/components/reporting/TaskReporting.tsx, client/react/app/components/reporting/TaskReportingTable.tsx, client/react/app/helpers/assessment.ts, client/react/app/helpers/reporting.ts, client/react/app/helpers/tasks.ts, server/api.js, server/db/controllers/tasks.js, server/db/models/task.js, server/db/models/user_assessment.js, server/db/models/utils.js
Adds more details to task reporting, moves more logic to the server.
=> Task reporting improvements

server/api.js, server/db/controllers/assessment_questions.js, server/db/controllers/index.js, server/db/index.js, server/db/models/assessment_question.js, server/db/models/scorecard.js
=> Set up assessment question analytics APIs

client/react/app/components/reporting/AssessmentReportingTable.tsx, client/react/app/components/reporting/MoodReporting.tsx, client/react/app/helpers/assessment.ts, client/react/app/helpers/reporting.ts, server/api.js, server/db/controllers/assessment_questions.js, server/db/models/assessment_question.js
Provide more informative data in mood analytics view.
Example:
=> Mood analytics improvements

client/react/app/components/reporting/Reporting.tsx, client/react/app/helpers/assessment.ts, client/react/app/helpers/reporting.ts, server/api.js, server/db/controllers/reporting.js, server/db/index.js, server/db/models/assessment.js, server/db/models/reporting.js, server/db/models/utils.js
=> API for correlation coefficients

client/react/app/components/reporting/CorrelationCoefficients.tsx, client/react/app/components/reporting/Reporting.tsx, client/react/app/helpers/reporting.ts
=> Simple correlation coefficients UI component

server/api.js, server/db/controllers/reporting.js, server/db/models/assessment.js, server/db/models/scorecard.js
=> Set up monthly averages APIs

client/react/app/components/reporting/AssessmentReportingTable.tsx
Based on tasks unique to highest score.
=> Additional suggestions per assessment question

client/react/app/components/reporting/AssessmentReportingTable.tsx, client/react/app/components/reporting/MoodReporting.tsx
Just outputs to console for now.
=> Top overall mood suggestions

client/react/app/components/reporting/TaskReportingTable.tsx
Sort by overall happiness instead of wellness score.
=> Task analytics updates
